# Site settings
title: Abhishek Sachan
subtitle: "_Front-end Geek"
email: iamabhishekfromindia@gmail.com
description: "Abhishek Sachan is a front-end Web Developer from India"
baseurl: ""
url: "http://abhisheksachan.in"
twitter_username: "AbhishekSachan3"
github_username:  "abhisack"
instagram_username: "abhisack"

# Build settings
markdown: kramdown
permalink: pretty

# Pagination
paginate: 5

# Sass
sass:
    style: :compressed